services:
  - type: web
    name: my-deep-learning-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.7.9
    staticPublishPath: static
